
workspace 'WhiteTownUIDemo'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
# ignore all warnings from all pods
inhibit_all_warnings!
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'WhiteTownUIDemo' do
  project 'WhiteTownUIDemo.xcodeproj'

#  pod 'WhiteTownUI'
#  pod 'WhiteTownUI',  :git => 'https://github.com/whitetown/WhiteTownUI.git'
#  pod 'WhiteTownUI',  :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
